name: Generate release
description: 'Generate next release version and notes'
author: Alexey Chekulaev
inputs:
  changelog_file:
    description: 'CHANGELOG.md file path. Pass empty string to disable changelog generation'
    default: CHANGELOG.md
    required: false
  changelog_title:
    description: 'Title of the changelog file (first line of the file)'
    required: false
  npm_extra_deps: # if use hyphens, then can't mock in integration tests
    description: 'Additional npm dependencies, used to install non-default commit parsers such as conventional-changelog-conventionalcommits@9.1.0'
    required: false
  release_branches:
    required: false
    description: 'The branches on which releases should happen. It will override the branches attribute in your configuration file'
  release_plugins:
    description: 'Release plugins configuration'
    required: false
  tag_format:
    description: 'Tag format. Default: v${version}'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'

outputs:
  channel:
    description: 'The release channel generated by the action based on commits since last release tag'
  git_tag:
    description: 'The next release version generated by the action based on commits since last release tag'
  notes_file:
    description: 'File with release notes generated by the action based on commits since last release tag'
  type:
    description: 'prerelease | prepatch | patch | preminor | minor | premajor" | major'

# Node 20 is max as of June 2025
# https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-javascript-action
# https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions
