name: Generate release
description: 'Generate next release version and notes'
author: Alexey Chekulaev
inputs:
  changelog_file:
    description: 'CHANGELOG.md file path. Pass empty string to disable changelog generation'
    required: false
    default: CHANGELOG.md
  changelog_title:
    description: 'Title of the changelog file (first line of the file)'
    required: false
  notes_tmp_file:
    description: 'Temporary file to store release notes'
    required: false
    default: /tmp/release-gen-notes
  npm_extra_deps:
    description: 'Additional npm dependencies, used to install non-default commit parsers such as conventional-changelog-conventionalcommits@9.1.0'
    required: false
  release_branches:
    required: false
    description: 'The branches on which releases should happen. It will override the branches attribute in your configuration file'
  release_plugins:
    description: 'Release plugins configuration'
    required: false
  tag_format:
    description: 'Tag format. Default: v${version}'
    required: false
  version:
    description: 'Version to release. If not specified, the version will be calculated based on commits since last release tag'
    required: false
  version_bump:
    description: 'Allows to bump a version w/o semantic commits'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'

outputs:
  channel: # 1) used in 'git notes' to power prerelease flow; 2) used in 'npm publish --tag'
    description: 'Release channel such as latest (for main branch), next (for prerelease) or support (for maintenance)'
  version:
    description: 'The next release version generated by the action based on commits since last release tag'
  git_tags:
    description: 'Space-separated git tags to create'
  notes_tmp_file:
    description: 'Equal to corresponding input, just for convenience'
  prerelease:
    description: 'Whether the release is a prerelease or not'
  tags:
    description: 'Space-separated tags to create: git_tags + branch name'

# Node 20 is max as of June 2025
# https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-javascript-action
# https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions
