name: Release

on:
  push:
    branches:
      - main
      - 1.x.x

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    with:
      artifacts: true
    secrets: inherit

  Release:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download artifacts
        uses: actions/download-artifact@v4
        # after this we have changes in file dist/index.js

      - name: Release
        uses: agilecustoms/release@next
        with:
          npm-extra-deps: conventional-changelog-conventionalcommits@9.1.0
        env:
          GH_TOKEN: ${{ secrets.GH_PUBLIC_RELEASES_TOKEN }}
