name: Release

on:
  push:
    branches:
      - main
      - 1.x.x

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    with:
      artifacts: true
    permissions:
      contents: write # needs "write" GH_TOKEN to _probe_ git push in semantic-release

  Release:
    needs: Build
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist

      - name: Release
        uses: agilecustoms/release@next
        with:
          npm-extra-deps: conventional-changelog-conventionalcommits@9.1.0
        env:
          GH_TOKEN: ${{ secrets.GH_PUBLIC_RELEASES_TOKEN }}
